import json

# Define your list of headquarters strings
headquarters_list = [
    "Headquarters:",
    "Headquarters: Ajax, Canada",
    "Headquarters: Albertville, AL",
    "Headquarters: Alpharetta, GA",
    "Headquarters: American Fork, UT",
    "Headquarters: Arnprior, Canada",
    "Headquarters: Attleboro, MA",
    "Headquarters: Auburn Hills, MI",
    "Headquarters: Aurora, Canada",
    "Headquarters: Australia",
    "Headquarters: Austria",
    "Headquarters: Ayer's Cliff, Canada",
    "Headquarters: Azusa, CA",
    "Headquarters: Barrie, Canada",
    "Headquarters: Bartlett, IL",
    "Headquarters: Bedford, NH",
    "Headquarters: Belgium",
    "Headquarters: Belleville, Canada",
    "Headquarters: Belleville, NJ",
    "Headquarters: Beloeil, Canada",
    "Headquarters: Bethlehem, PA",
    "Headquarters: Blasdell, NY",
    "Headquarters: Bloomington, IL",
    "Headquarters: Boisbriand, Canada",
    "Headquarters: Bolingbrook, IL",
    "Headquarters: Boston, MA",
    "Headquarters: Boucherville, Canada",
    "Headquarters: Bracebridge, Canada",
    "Headquarters: Brampton, Canada",
    "Headquarters: Brandon, FL",
    "Headquarters: Brantford, Canada",
    "Headquarters: Brazil",
    "Headquarters: Buena, NJ",
    "Headquarters: Buffalo, NY",
    "Headquarters: Burlington, Canada",
    "Headquarters: Caledon, Canada",
    "Headquarters: Calgary, Canada",
    "Headquarters: Cambodia",
    "Headquarters: Cambridge, Canada",
    "Headquarters: Campbell River, Canada",
    "Headquarters: Canada",
    "Headquarters: Canandaigua, NY",
    "Headquarters: Cary, IL",
    "Headquarters: Ceres, CA",
    "Headquarters: Chanhassen, MN",
    "Headquarters: Charlotte, NC",
    "Headquarters: Chicago, IL",
    "Headquarters: China",
    "Headquarters: Cincinnati, OH",
    "Headquarters: Clifton, NJ",
    "Headquarters: Colchester, CT",
    "Headquarters: Colorado Springs, CO",
    "Headquarters: Concord , Canada",
    "Headquarters: Concord, Canada",
    "Headquarters: Conover, NC",
    "Headquarters: Cookeville, TN",
    "Headquarters: Coppell, TX",
    "Headquarters: Coquitlam, Canada",
    "Headquarters: Cornwall, Canada",
    "Headquarters: Czech Republic",
    "Headquarters: Dallas, TX",
    "Headquarters: Dartmouth, Canada",
    "Headquarters: Delta, Canada",
    "Headquarters: Denmark",
    "Headquarters: Dorval, Canada",
    "Headquarters: Doylestown, PA",
    "Headquarters: Dubois, PA",
    "Headquarters: Dundas, Canada",
    "Headquarters: Duryea, PA",
    "Headquarters: Edmonton, Canada",
    "Headquarters: El Cajon, CA",
    "Headquarters: Elk Grove Village, IL",
    "Headquarters: Elmira, Canada",
    "Headquarters: Erlanger, KY",
    "Headquarters: Escondido, CA",
    "Headquarters: Etobicoke, Canada",
    "Headquarters: Farmington, CT",
    "Headquarters: Finland",
    "Headquarters: Fort Mill, SC",
    "Headquarters: France",
    "Headquarters: Franklin, MA",
    "Headquarters: Garland, TX",
    "Headquarters: Georgetown, MA",
    "Headquarters: Germantown, WI",
    "Headquarters: Germany",
    "Headquarters: Glasgow, KY",
    "Headquarters: Granby, Canada",
    "Headquarters: Grand Prairie, TX",
    "Headquarters: Grand Rapids, MI",
    "Headquarters: Greenville, SC",
    "Headquarters: Greenwood, DE",
    "Headquarters: Guelph, Canada",
    "Headquarters: Gurnee, IL",
    "Headquarters: Hamilton, Canada",
    "Headquarters: Hamilton, OH",
    "Headquarters: Highland, UT",
    "Headquarters: Holland, OH",
    "Headquarters: Hong Kong",
    "Headquarters: Honolulu, HI",
    "Headquarters: Hubbards, Canada",
    "Headquarters: Hudson, OH",
    "Headquarters: Hyannis, MA",
    "Headquarters: Iceland",
    "Headquarters: India",
    "Headquarters: Indonesia",
    "Headquarters: Ingleside, IL",
    "Headquarters: Ireland",
    "Headquarters: Irwin, PA",
    "Headquarters: Israel",
    "Headquarters: Italy",
    "Headquarters: Japan",
    "Headquarters: Jordan",
    "Headquarters: Kenilworth, NJ",
    "Headquarters: Kingsey Falls, Canada",
    "Headquarters: Kingston, Canada",
    "Headquarters: Kitchener, Canada",
    "Headquarters: Korea, South",
    "Headquarters: La Crosse, WI",
    "Headquarters: Lachine, Canada",
    "Headquarters: Laconia, NH",
    "Headquarters: Lake Zurich, IL",
    "Headquarters: Lancaster, OH",
    "Headquarters: Lantzville, Canada",
    "Headquarters: Las Vegas, NV",
    "Headquarters: Laurens, IA",
    "Headquarters: Laval, Canada",
    "Headquarters: Lebanon, OH",
    "Headquarters: Lewiston, ME",
    "Headquarters: Lewisville, NC",
    "Headquarters: Lewisville, TX",
    "Headquarters: Lexington, KY",
    "Headquarters: Libertyville, IL",
    "Headquarters: Lincoln, RI",
    "Headquarters: London, Canada",
    "Headquarters: Louisa, VA",
    "Headquarters: Madison, WI",
    "Headquarters: Malaysia",
    "Headquarters: Mansfield, TX",
    "Headquarters: Markham, Canada",
    "Headquarters: McHenry, IL",
    "Headquarters: Melbourne, FL",
    "Headquarters: Menomonee Falls, WI",
    "Headquarters: Mexico",
    "Headquarters: Michigan City, IN",
    "Headquarters: Middlefield, OH",
    "Headquarters: Milton, Canada",
    "Headquarters: Milwaukee, WI",
    "Headquarters: Minneapolis, MN",
    "Headquarters: Minooka, IL",
    "Headquarters: Mississauga, Canada",
    "Headquarters: Moncton , Canada",
    "Headquarters: Montreal, Canada",
    "Headquarters: Morgantown, PA",
    "Headquarters: Morristown, TN",
    "Headquarters: Netherlands",
    "Headquarters: Nevada, IA",
    "Headquarters: New Berlin, WI",
    "Headquarters: New Westminster, Canada",
    "Headquarters: New Zealand",
    "Headquarters: Newmarket, Canada",
    "Headquarters: Newtown Square, PA",
    "Headquarters: Niagara Falls, Canada",
    "Headquarters: Niagara on the Lake, Canada",
    "Headquarters: North Ridgeville, OH",
    "Headquarters: North Vancouver, Canada",
    "Headquarters: Norway",
    "Headquarters: Oakville, Canada",
    "Headquarters: Oldcastle, Canada",
    "Headquarters: Ottawa, Canada",
    "Headquarters: Paterson, NJ",
    "Headquarters: Peachtree Corners, GA",
    "Headquarters: Perry, OH",
    "Headquarters: Philadelphia, PA",
    "Headquarters: Phoenix, AZ",
    "Headquarters: Pickering, Canada",
    "Headquarters: Plano, TX",
    "Headquarters: Plymouth, MI",
    "Headquarters: Poland",
    "Headquarters: Pont-Rouge, Canada",
    "Headquarters: Port Hope, Canada",
    "Headquarters: Portugal",
    "Headquarters: Providence, RI",
    "Headquarters: Redlands, CA",
    "Headquarters: Richmond Hill, Canada",
    "Headquarters: Richmond, Canada",
    "Headquarters: Richmond, VA",
    "Headquarters: Rockland, MA",
    "Headquarters: Roswell, GA",
    "Headquarters: Russia",
    "Headquarters: Saint Eustache, Canada",
    "Headquarters: Saint-Alphonse-de-Granby, Canada",
    "Headquarters: Saint-Eustache, Canada",
    "Headquarters: Saint-Francois, Canada",
    "Headquarters: Saint-Lazare, Canada",
    "Headquarters: Sainte-Anne-de-Bellevue, Canada",
    "Headquarters: Sainte-Julie, Canada",
    "Headquarters: Sainte-Marie, Canada",
    "Headquarters: Salem, OR",
    "Headquarters: San Diego, CA",
    "Headquarters: San Jose, CA",
    "Headquarters: San Marino",
    "Headquarters: Sandy, UT",
    "Headquarters: Sarasota, FL",
    "Headquarters: Saudi Arabia",
    "Headquarters: Scarborough, Canada",
    "Headquarters: Scottdale, GA",
    "Headquarters: Serbia",
    "Headquarters: Shippagan, Canada",
    "Headquarters: Simi Valley, CA",
    "Headquarters: Singapore",
    "Headquarters: Solon, OH",
    "Headquarters: Somerville, NJ",
    "Headquarters: Spain",
    "Headquarters: Springfield, TN",
    "Headquarters: St. Bruno, Canada",
    "Headquarters: St. Charles, IL",
    "Headquarters: St. Georges, Canada",
    "Headquarters: St. Hubert, Canada",
    "Headquarters: St. John's, Canada",
    "Headquarters: St. Laurent, Canada",
    "Headquarters: Stafford Springs, CT",
    "Headquarters: Sterling Heights, MI",
    "Headquarters: Sterling, IL",
    "Headquarters: Stoney Creek, Canada",
    "Headquarters: Stratford, CT",
    "Headquarters: Streetsboro, OH",
    "Headquarters: Sweden",
    "Headquarters: Switzerland",
    "Headquarters: Taiwan",
    "Headquarters: Terre Haute, IN",
    "Headquarters: Terrebonne, Canada",
    "Headquarters: Thailand",
    "Headquarters: Thomasville, NC",
    "Headquarters: Thunder Bay, Canada",
    "Headquarters: Toronto, Canada",
    "Headquarters: Totowa, NJ",
    "Headquarters: Trois-Rivieres, Canada",
    "Headquarters: Troy, MI",
    "Headquarters: Troy, NY",
    "Headquarters: Turkey",
    "Headquarters: Twinsburg, OH",
    "Headquarters: United Kingdom",
    "Headquarters: United States",
    "Headquarters: Uxbridge, Canada",
    "Headquarters: Valley City, OH",
    "Headquarters: Valley Stream, NY",
    "Headquarters: Vancouver, Canada",
    "Headquarters: Vernon, AL",
    "Headquarters: Victoria, Canada",
    "Headquarters: Warminster, PA",
    "Headquarters: Waterloo, Canada",
    "Headquarters: Waukegan, IL",
    "Headquarters: West Chester, PA",
    "Headquarters: Westchester, IL",
    "Headquarters: Wilmington, NC",
    "Headquarters: Windsor, Canada",
    "Headquarters: Winnipeg, Canada",
    "Headquarters: Winston Salem, NC",
    "Headquarters: Winthrop, ME",
    "Headquarters: Wolcott, IN",
    "Headquarters: Woodbridge, Canada",
    "Headquarters: Woodstock, Canada",
    "Headquarters: Wyoming, MI",
    "Headquarters: York, PA",
    "Headquarters: Yorktown, VA"
]

def is_us_or_canada(hq_str, us_states):
    """
    Returns True if the headquarters string appears to be located in the US or Canada.
    Criteria:
      - The string must contain "Canada" OR
      - The string must contain "United States" OR "US" OR
      - If there's a comma, the part after the comma is checked against a set of US state abbreviations.
    """
    # Remove the prefix "Headquarters:" and extra spaces
    text = hq_str.replace("Headquarters:", "").strip()
    if not text:
        return False

    # Check if text explicitly mentions Canada or United States
    if "Canada" in text:
        return True
    if "United States" in text or text == "US":
        return True

    # If there's a comma, assume the part after the comma is a location
    if "," in text:
        parts = text.split(",")
        if len(parts) >= 2:
            location = parts[1].strip()
            if location in us_states:
                return True
    return False

def main():
    # Define US state abbreviations
    us_states = {
        "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
        "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
        "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
        "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
        "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"
    }
    
    # Filter the headquarters list
    filtered = [hq for hq in headquarters_list if is_us_or_canada(hq, us_states)]
    
    # Optionally, remove duplicates by converting to a set, then back to list (if order is not important)
    filtered_unique = sorted(list(set(filtered)))
    
    # Write the filtered list to a JSON file
    output_file = "us_canada_headquarters.json"
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(filtered_unique, f, indent=4)
    
    print(f"Filtered {len(filtered_unique)} headquarters. Output saved to {output_file}")

if __name__ == "__main__":
    main()
